services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: company
      TZ: "Asia/Kolkata"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.140.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config/otel-config.yml:/etc/otelcol-contrib/config.yaml
    environment:
      - BASE14_SCOUT_ENDPOINT=${BASE14_SCOUT_ENDPOINT}
      - BASE14_CLIENT_ID=${BASE14_CLIENT_ID}
      - BASE14_CLIENT_SECRET=${BASE14_CLIENT_SECRET}
      - BASE14_TOKEN_URL=${BASE14_TOKEN_URL}
    restart: unless-stopped

  spring-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      mongodb:
        condition: service_healthy
      otel-collector:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/company
      SPRING_DATA_MONGODB_DATABASE: company
      SPRING_APPLICATION_NAME: java-spring-boot-otel-mongodb
      OTEL_SERVICE_NAME: java-spring-boot-otel-mongodb
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_RESOURCE_ATTRIBUTES: service.name=java-spring-boot-otel-mongodb,service.namespace=base14,environment=dev,service.version=0.0.1-SNAPSHOT
      OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: true
      OTEL_INSTRUMENTATION_HTTP_ENABLED: true
      OTEL_INSTRUMENTATION_SERVLET_ENABLED: true
      OTEL_INSTRUMENTATION_SPRING_WEB_ENABLED: true
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED: true
      OTEL_INSTRUMENTATION_SPRING_WEBMVC_CONTROLLER_ENABLED: true
      OTEL_INSTRUMENTATION_ANNOTATIONS_ENABLED: true
    restart: unless-stopped

volumes:
  mongodb_data:
