default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: 3306
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "rootpassword") %>

development:
  <<: *default
  database: rails_otel_dev

test:
  <<: *default
  database: rails_otel_test
